name: FTinker
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  redux_thunk: ^0.2.1
  rxdart: ^0.22.1+1
  http: ^0.12.0+2

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    path: /Library/flutter_web
  flutter_web_ui:
    path: /Library/flutter_web_ui
  flutter_web_test:
    path: /Library/flutter_web_test